language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jud/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jud/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    brach: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY